- name: create a bastion machine
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
   - name: Import  variable
     include_vars: bastion_ami

   - name: import vpc variable
     include_vars: vpc_varibles
    
   - name: create key pair
     ec2_key:
      name: sample_key
      state: present
      region: "{{region}}"
     register: key_out

   - name: save the key in local machine
     copy:
      source: "{{key_out.key.private_key}}"
      dest: "./bastion_keys"
      mode: 600
     when: key_out.changed

   - name: create security group
     ec2_security_group:
      description: create a bastion host to allow only port 22
      name: bastion_group
      region: "{{ region }}"
      rules:
       - cidr_ip: "{{ MYIP }}"
         proto: tcp
         from_port: 22
         to_port: 22
      state: present
      vpc_id: "{{ vpc_id }}"
     register: bastionsg_out

   - name: create ec2 instance
     ec2_instance:
      state: present
      name: sample_instance
      region: "{{ region }}"
      instance_type: t2.micro
      image: "{{ bastion_ami }}"
      key_name: sample_key
      instance_tags:
       Name: "bastion_host"
       Project: vprofile
       Owner: Devops_team
      exact_count: 1
      count_tag:
       Name: "bastion_host"
       Project: vprofile
       Owner: Devops_team
      security_group: "{{ bastionsg_ou.group_id }}"
      vpc_subnet_id: "{{ pubsub1id }}"
     register: bastionhost_out
