- hosts: localhost
  connection: local
  tasks:
  - name: Import VPC varibles
    include_vars: variable

  - name: create vprofile VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      dns_hostnames: true
      dns_support: true
    register: vpcout

  - debug:
     var: vpcout

  - name: create prvt subnet1
    ec2_vpc_subnet:
      cidr: "{{PubSub1Cdir}}"
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      map_public: false
      region: "{{region}}"
      az: "{{zone1}}"
      resource_tags:
       Name: vprofile_privsub1
    register: privsub_out1

  - name: create pvrt subnet2
    ec2_vpc_subnet:
      cidr: "{{PubSub2Cdir}}"
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      map_public: false
      region: "{{region}}"
      az: "{{zone2}}"
      resource_tags:
       Name: vprofile_privsub2
    register: privsub_out2

  - name: create prvt subnet3
    ec2_vpc_subnet:
      cidr: "{{PubSub3Cdir}}"
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      map_public: false
      region: "{{region}}"
      az: "{{zone3}}"
      resource_tags:
       Name: vprofile_privsub3
    register: privsub_out3

  - name: create pub subnet1
    ec2_vpc_subnet:
     cidr: "{{PubSub4Cdir}}"
     state: present
     vpc_id: "{{vpcout.vpc.id}}"
     region: "{{region}}"
     map_public: true
     az: "{{zone1}}"
     resource_tags:
      Name: vprofile_pubsub1
    register: pubsub_out1
  
  - name: create pub subnet2
    ec2_vpc_subnet:
     cidr: "{{PubSub5Cdir}}"
     state: present
     vpc_id: "{{vpcout.vpc.id}}"
     region: "{{region}}"
     map_public: true
     az: "{{zone2}}"
     resource_tags:
      Name: vprofile_pubsub2
    register: pubsub_out2

  - name: create pub subnet3
    ec2_vpc_subnet:
     cidr: "{{PubSub6Cdir}}"
     state: present
     vpc_id: "{{vpcout.vpc.id}}"
     region: "{{region}}"
     map_public: true
     az: "{{zone3}}"
     resource_tags:
      Name: vprofile_pubsub3
    register: pubsub_out3


  - name: create gateway setup
    ec2_vpc_igw:
     vpc_id: "{{vpcout.vpc.id}}"
     state: present
     region: "{{region}}"
     resource_tags:
      Name: vprofile_IGW
    register: igw_out
  - debug:
     var: igw_out

  - name: create route table
    ec2_vpc_route_table:
     region: "{{region}}"
     vpc_id: "{{vpcout.vpc.id}}"
     state: present
     resource_tags:
      Name: public
     routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{igw_out.gateway_id}}"
     subnets:
      - "{{pubsub_out1.subnet.id}}"
      - "{{pubsub_out2.subnet.id}}"
      - "{{pubsub_out3.subnet.id}}"
    register: pub_rt
  - debug:
     var: pub_rt

  - name: create a nat gateway
    ec2_vpc_nat_gateway:
     state: present
     subnet_id: "{{pubsub_out1.subnet.id}}"
     if_exist_do_not_create: true
     wait: true
     region: "{{region}}"
    register: NATGW_out

  - debug:
     var: NATGW_out

  - name: creata internet gate way to NAT gate
    ec2_vpc_route_table:
     region: "{{region}}"
     vpc_id: "{{vpcout.vpc.id}}"
     state: present
     resource_tags:
      Name: vprofile_public
     routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ NATGW_out.nat_gateway_id }}"
     subnets:
      - "{{privsub_out1.subnet.id}}"
      - "{{privsub_out2.subnet.id}}"
      - "{{privsub_out3.subnet.id}}"
    register: privRT_out
  - debug:
     var: privRT_out
  
  - debug:
      var: "{{item}}"
    loop:
     - vpcout.vpc.id
     - pubsub_out1.subnet.id
     - pubsub_out2.subnet.id
     - pubsub_out3.subnet.id
     - privsub_out1.subnet.id
     - privsub_out2.subnet.id
     - privsub_out3.subnet.id
     - igw_out.gateway_id
     - pub_rt.route_table.id
     - NATGW_out.nat_gateway_id
     - privRT_out.route_table.id

  - set_fact:
     vpc_id: "{{vpcout.vpc.id}}"
     pubsub1id: "{{pubsub_out1.subnet.id}}"
     pubsub2id: "{{pubsub_out2.subnet.id}}"
     pubsub3id: "{{pubsub_out3.subnet.id}}"
     privsub1id: "{{privsub_out1.subnet.id}}"
     privsub2id: "{{privsub_out2.subnet.id}}"
     privsub3id: "{{privsub_out3.subnet.id}}"
     igwid: "{{igw_out.gateway_id}}"
     pubRTid: "{{pub_rt.route_table.id}}"
     NATGWid: "{{NATGW_out.nat_gateway_id}}"
     privRTid: "{{privRT_out.route_table.id}}"
     cacheable: yes

  - name: create varible file after vpc igw_out
    copy:
     content: "vpc_id: {{vpcout.vpc.id}}\npubsub1id: {{pubsub_out1.subnet.id}}\npubsub2id: {{pubsub_out2.subnet.id}}\npubsub3id: {{pubsub_out3.subnet.id}}\nprivsub1id: {{privsub_out1.subnet.id}}\nprivsub2id: {{privsub_out2.subnet.id}}\nprivsub3id: {{privsub_out3.subnet.id}}\nigwid: {{igw_out.gateway_id}}\npubRTid: {{pub_rt.route_table.id}}\nNATGWid: {{NATGW_out.nat_gateway_id}}\nprivRTid: {{privRT_out.route_table.id}}"
     dest: "/VPCproject/vpc_variables_out"
