- hosts: localhost
  connection: local
  tasks:
  - name: Import VPC varibles
    include_vars: variable

  - name: create vprofile VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      dns_hostnames: true
      dns_support: true
    register: vpcout

  - debug:
     var: vpcout

  - name: create prvt subnet1
    ec2_vpc_subnet:
      cidr: "{{PubSub1Cdir}}"
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      map_public: false
      region: "{{region}}"
      az: "{{zone1}}"
      resource_tags:
       Name: vprofile_privsub1
    register: privsub_out1

  - name: create pvrt subnet2
    ec2_vpc_subnet:
      cidr: "{{PubSub2Cdir}}"
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      map_public: false
      region: "{{region}}"
      az: "{{zone2}}"
      resource_tags:
       Name: vprofile_privsub2
    register: privsub_out2

  - name: create prvt subnet3
    ec2_vpc_subnet:
      cidr: "{{PubSub3Cdir}}"
      state: present
      vpc_id: "{{vpcout.vpc.id}}"
      map_public: false
      region: "{{region}}"
      az: "{{zone3}}"
      resource_tags:
       Name: vprofile_privsub3
    register: privsub_out3

  - name: create pub subne1
    ec2_vpc_subnet:
     cidr: "{{PubSub4Cdir}}"
     state: present
     vpc_id: "{{vpcout.vpc.id}}"
     region: "{{region}}"
     map_public: true
     az: "{{zone1}}"
     resource_tags:
      Name: vprofile_pubsub1
    register: pubsub_out1
  
  - name: create pub subne2
    ec2_vpc_subnet:
     cidr: "{{PubSub5Cdir}}"
     state: present
     vpc_id: "{{vpcout.vpc.id}}"
     region: "{{region}}"
     map_public: true
     az: "{{zone2}}"
     resource_tags:
      Name: vprofile_pubsub2
    register: pubsub_out2

  - name: create pub subne3
    ec2_vpc_subnet:
     cidr: "{{PubSub6Cdir}}"
     state: present
     vpc_id: "{{vpcout.vpc.id}}"
     region: "{{region}}"
     map_public: true
     az: "{{zone3}}"
     resource_tags:
      Name: vprofile_pubsub3
    register: pubsub_out3


  - name: create gateway setup
    ec2_vpc_igw:
     vpc_id: "{{vpcout.vpc.id}}"
     state: present
     region: "{{region}}"
     resource_tags:
      Name: vprofile_IGW
    register: igw_out
  - debug:
    var: igw_out

  - name: create route table
    amazon.aws.ec2_vpc_route_table:
     region: "{{region}}"
     vpc_id: "{{vpcout.vpc.id}}"
     state: present
     resource_tags:
      Name: public
     routes:
      - dest: 0.0.0.0./0
        gateway_id: "{{igw_out.gateway_id}}"
     subnets:
      - "{{privsub_out1.subnet.id}}"
      - "{{privsub_out2.subnet.id}}"
      - "{{privsub_out3.subnet.id}}"
    register: vprofile_rt
  - debug:
     var: vprofile_rt

  - name: create a nat gateway
    ec2_vpc_nat_gateway:
     resource_tags:
      Name: vprofile_gateway
     state: present
     subnet_id: "{{pubsub_out1.subnet.id}}"
     if_exist_do_not_creat: true
     wait: true
     region: "{{region}}"
    register: NATGW_out

  - debug:
     var: NATGW_out

  - name: creat internet gate way to NAT gate
    ec2_vpc_igw:
     region: "{{region}}"
     vpc_id: "{{vpcout.vpc.id}}"
     state: present
     resource_tags:
      Name: vprofile_public
     routes:
      - dest: 0.0.0.0./0
        gateway_id: "{{ NATGW_out.nat_gateway_id }}"
     subnets:
      - "{{privsub_out1.subnet.id}}"
      - "{{privsub_out2.subnet.id}}"
      - "{{privsub_out3.subnet.id}}"
    register: privRT_out
  - debug:
     var: privRT_out
  
